import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		
		
		// Initailizes a random numbers generator with the given seed value
     
		
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

		int t = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		Random generator = new Random(seed);  
		
		double sum_all= 0.0;
		double averege = 0.0;
		int twochildren = 0;
		int threechildren = 0;
		int fourchildren = 0;
		String common ;
		
			for (int i = 0; i < t; i++){
				boolean girl = false; 
				boolean boy = false;
				int sum = 0;
				while(girl == false || boy == false){
					double a = generator.nextDouble();
					if (a >= 0.5){
						girl = true;
					}

					else {
						boy = true;
					}
					sum ++ ;
			}
			sum_all += sum;	
			if (sum == 2) {	
				twochildren ++;
			}
			else if (sum == 3) {
				threechildren ++;
			}
			else if (sum >= 4) {
				fourchildren ++;
			}
			
		}
		
		averege = sum_all / t ; 

		if (twochildren >= threechildren && twochildren >= fourchildren){
			common = "2.";
		}
		else if (threechildren >= twochildren && threechildren >= fourchildren){
			common = "3.";
		}
		else{
			common="4 or more.";
		}
		
		System.out.println("Average: " + averege + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+ twochildren);
		System.out.println("Number of families with 3 children: "+ threechildren);
		System.out.println("Number of families with 4 or more children: "+ fourchildren);
		System.out.println("The most common number of children is "+ common);
	}
}





		
			
